name: CI-CD nginx node js
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Permission bash
        run: chmod +x start.sh 

      - name: Permission bash
        run: chmod +x start.dev.sh 

      - name: paste in aplication
        run: cd app


      - name: install packges
        run: npm install

      - name: Build image 
        run: docker build -t app .
